### ISSUE TITLE
Activate tls without supplying a ca file

### ISSUE THREAD

**Issue by hobbyquaker** [jpmens/check-mqtt#10]
Do I understand it right that I have to supply a ca file to activate a tls connection? If yes - would it make sense to add another command line option to activate tls without supplying a ca file?

**Comment by jpmens** [comment]
TLS without a CA is useless; who's going to verify the trustworthyness of your endpoint? You need a CA certificate to do that.

**Comment by hobbyquaker** [comment]
The CA cert is already in the systems truststore?

**Comment by jpmens** [comment]
Then you'll need an option to specify the path to that system trust store

**Comment by hobbyquaker** [comment]
ah ok, that will not be that much benefit, doesn't really matter if i supply the specific cert or the trusststore path. I'm used to the nodejs tls module, that supplies it's own (mozilla based) truststore i learned right now, so I never had to take care of this... But I see, mosquitto_sub/pub e.g. handle it the same way, one has to supply cafile or capath... So never mind, I'm closing the issue :)
