### ISSUE TITLE
Falsewarning

### ISSUE THREAD

**Issue by sRlinux** [jpmens/check-mqtt#12]
I get a wrong warning if value is below 10

root@openhab:~# /usr/lib/nagios/plugins/check_mqtt -H 192.168.20.10 -P 1883 -u openhab -p XXXXX -t sensor2_temp0 -o lessthan -v 50 -S
CRITICAL - value=9 | response_time=0.00 value=9

**Comment by jpmens** [comment]
closed via https://github.com/jpmens/check-mqtt/pull/13
