### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by Banzai292** [jpmens/check-mqtt#20]
For everyone who requires support for Python 3, please change following lines (from commit c4fa7d6ac7537ac09fd05101e8709fab9e920dad):

- Line 1: `#!/usr/bin/env python3`
- Line 131: `payload = msg.payload.decode("utf-8")`
- Line 200: `print ('%s - %s' % (nagios_codes[status], message))`
- Line 285: `except (Exception, e):`

The changes on line 131 are required, if broker sends UTF-8 back, because payload will then be like b'foo' instead of 'foo'.

Hope someone find this useful and sometimes this behaviour will implemented.

Cheers

**Comment by jpmens** [comment]
I will accept a pull-request which implements this, in particular because Python2 is going away fast.
