### ISSUE TITLE
Invalid protocol

### ISSUE THREAD

**Issue by raymonvdm** [jpmens/check-mqtt#5]
I`m using the check for some time on my own nagios and it is working fine. However i have added an new MQTT server and a check on another nagios server and it is not working correctly 

It seems to be related to the version of the MQTT broker. (old nagios machine with new broker als gives issues) Is this something which should be fixed in the check because the broker itself seems to be working ok.

I have installed the broker on a fresh Ubuntu 14.04 LTS machine

`
sudo add-apt-repository ppa:mosquitto-dev/mosquitto-ppa
apt-get install mosquitto mosquitto-clients python-mosquitto
`

`
dpkg -l | grep mosq
ii  libmosquitto0                       0.15-2ubuntu1                    amd64        MQTT version 3.1 client library
ii  mosquitto                           0.15-2ubuntu1                    amd64        MQTT version 3.1 compatible message broker
ii  mosquitto-clients                   0.15-2ubuntu1                    amd64        Mosquitto command line MQTT clients
ii  python-mosquitto                    0.15-2ubuntu1                    all          MQTT version 3.1 client library, python bindings

`

This is the version on the "old" machine

`
dpkg -l | grep mosq
ii  libmosquitto0                         0.15-2ubuntu1                           i386         MQTT version 3.1 client library
ii  libmosquitto1:i386                    1.4.8-0mosquitto1                       i386         MQTT version 3.1/3.1.1 client library
ii  mosquitto                             1.4.8-0mosquitto1                       i386         MQTT version 3.1/3.1.1 compatible message broker
ii  mosquitto-clients                     1.4.8-0mosquitto1                       i386         Mosquitto command line MQTT clients
ii  python-mosquitto                      1.3.5-0ppa1                             all          MQTT version 3.1 Python client library
`

To verify the source of the package that is used i used this command
`apt-cache showpkg mosquitto`

And it seems to be the Ubuntu version and not the PPA version. So there is also one issue on my side at least

**Comment by jpmens** [comment]
`mosquitto 0.15` is ancient. Upgrade. Or modify line 106 to specify `protocol=3` or no protocol.
No change required here.
